### ISSUE TITLE
nightmode module

### ISSUE THREAD

**Issue by demostanis** [luakit/luakit.github.io#4]
What is it? Why is it in the documentation? I can't find it in luakit's source code.

**Comment by c0dev0id** [comment]
Hi,
can you be more specific? In which documentation did you find the nightmode?

If you want websites to use the dark mode theme ([if available](https://css-tricks.com/dark-modes-with-css/)), you can enable `gtk-application-prefer-dark-theme` in `:settings`.

**Comment by demostanis** [comment]
Looks like it has been removed. Last revision:
https://github.com/luakit/luakit.github.io/blob/fd176044a0851dbd156617696fc09010db2e7b9c/docs/modules/nightmode.html

**Comment by aidanholm** [comment]
Oops, that's a personal module that leaked in when I regenerated the docs

I haven't upsteamed this, because it's very rudimentary, but [here's the source](https://gist.githubusercontent.com/aidanholm/0e17a4a418e377dc6fb257e5e854a4dc/raw/cda1d0b6c90d818a48f5229c0f47cbb5fbfe8ee3/nightmode.lua)
